eureka:
  instance:
     hostname: ${vcap.application.uris[0]}
     nonSecurePort: 80
  client:
    serviceUrl:
       defaultZone: http://eureka-server-spring.mybluemix.net/eureka/

# Spring properties
spring:
  application:
     name: hello-service

  # MySQL Data soure configuration
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://us-cdbr-iron-east-03.cleardb.net/ad_5bc9d4b23eb79bd?user=b6f241267bae0e&password=aa81b830
    username: b6f241267bae0e
    password: aa81b830
    max-active: 2
    testOnBorrow: true
    validationQuery: SELECT 1

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy


# Server configuration
server:
  context-path: /app
  port: 80
